<?php

namespace FluentComments\App\Hooks\Handlers;

use FluentComments\App\Helpers\Arr;
use FluentComments\App\Services\DiscussionSettings;
use FluentComments\App\Services\Helper;
use FluentComments\App\Services\TemplateScanner;
use FluentComments\App\Services\TransStrings;

class AdminSettingsHandler
{
    const PAGE_SLUG = 'fluent-comments';

    public function register()
    {
        add_action('admin_menu', [$this, 'addAdminMenu']);
        add_action('wp_ajax_fluent-comments-admin-save-settings', [$this, 'saveSettingsAjax']);
        add_action('wp_ajax_fluent-comments-admin-scan-templates', [$this, 'scanTemplatesAjax']);
        add_action('admin_notices', [$this, 'maybeShowSetupNotice']);
    }

    public function addAdminMenu()
    {
        add_submenu_page(
            'edit-comments.php',
            __('FluentComments', 'fluent-comments'),
            __('FluentComments', 'fluent-comments'),
            'manage_options',
            self::PAGE_SLUG,
            [$this, 'renderAdminPage']
        );
    }

    public function renderAdminPage()
    {
        // The email editor is a real wp.editor instance, so TinyMCE, the
        // quicktags toolbar and the media modal all have to be on the page
        // before the app mounts - none of them can be pulled in later.
        wp_enqueue_editor();
        wp_enqueue_media();

        wp_enqueue_style(
            'fluent_comments_admin',
            FLUENT_COMMENTS_PLUGIN_URL . 'dist/css/admin_app.css',
            [],
            FLUENT_COMMENTS_VERSION
        );

        wp_enqueue_script(
            'fluent_comments_admin',
            FLUENT_COMMENTS_PLUGIN_URL . 'dist/js/admin_app.js',
            ['jquery'],
            FLUENT_COMMENTS_VERSION,
            true
        );

        $postTypesWithComments = [];
        $globalDisabled = ['product', 'attachment', 'page'];

        foreach (get_post_types([], 'objects') as $postType) {
            if (in_array($postType->name, $globalDisabled, true)) {
                continue;
            }

            if (!$postType->public || !post_type_supports($postType->name, 'comments')) {
                continue;
            }

            $postTypesWithComments[$postType->name] = [
                'name'        => $postType->name,
                'title'       => $postType->label,
                'description' => $postType->description,
            ];
        }

        $settings = Helper::getCommentSettings();
        $settings['post_types'] = array_values(array_intersect($settings['post_types'], array_keys($postTypesWithComments)));

        // Loaded here rather than with the rest of the plugin: it is one
        // array of ~150 __() calls and this admin screen is the only thing
        // that ever asks for it.
        require_once FLUENT_COMMENTS_PLUGIN_PATH . 'app/Services/TransStrings.php';

        wp_localize_script('fluent_comments_admin', 'fluentCommentsVars', [
            'ajax_url'            => admin_url('admin-ajax.php'),
            'nonce'               => wp_create_nonce('fluent_comment_admin_nonce'),
            'version'             => FLUENT_COMMENTS_VERSION,
            'comments_post_types' => array_values($postTypesWithComments),
            'settings'            => $settings,
            'discussion'          => DiscussionSettings::get(),
            'discussion_url'      => admin_url('options-discussion.php'),
            'using_block_theme'   => Helper::isBlockTheme() ? 'yes' : 'no',
            // Every string the Vue app looks up by its English source
            // string. Generated by `npm run i18n` - see TransStrings.
            'i18n'                => TransStrings::getStrings(),
            'asset_url'           => FLUENT_COMMENTS_PLUGIN_URL . 'dist/',
            'links'               => [
                'docs'    => 'https://wordpress.org/plugins/fluent-comments/',
                'support' => 'https://wordpress.org/support/plugin/fluent-comments/',
                'rate'    => 'https://wordpress.org/support/plugin/fluent-comments/reviews/#new-post',
                'github'  => 'https://github.com/WPManageNinja/fluent-comments',
            ],
        ]);

        echo '<div class="wrap"><div id="fluent_comment_app"></div></div>';
    }

    public function saveSettingsAjax()
    {
        Helper::verifyAdminAjax();

        // The nonce and capability are verified by Helper::verifyAdminAjax() above,
        // and every value below is sanitized individually.
        // phpcs:disable WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
        $raw = isset($_POST['settings']) && is_array($_POST['settings'])
            ? wp_unslash($_POST['settings'])
            : [];
        // phpcs:enable WordPress.Security.NonceVerification.Missing, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized

        if (empty($raw)) {
            wp_send_json(['message' => __('Settings cannot be empty.', 'fluent-comments')], 400);
        }

        $defaults = Helper::getDefaultSettings();
        $raw = Arr::only($raw, array_keys($defaults));

        $postTypes = isset($raw['post_types']) && is_array($raw['post_types']) ? $raw['post_types'] : [];
        $postTypes = array_map('sanitize_key', array_filter($postTypes, 'is_scalar'));

        $settings = [
            'post_types' => array_values(array_unique(array_filter($postTypes, 'post_type_exists'))),
        ];

        foreach (['reject_native_comments', 'email_on_comment_approval', 'email_on_reply', 'email_to_author'] as $key) {
            $settings[$key] = (isset($raw[$key]) && $raw[$key] === 'yes') ? 'yes' : 'no';
        }

        update_option('_fluent_comments_settings', $settings);

        // Core's own options, written straight through so this screen and
        // Settings > Discussion can never disagree.
        if (isset($_POST['discussion']) && is_array($_POST['discussion'])) {
            // phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- update_option() runs sanitize_option() on every value.
            DiscussionSettings::save(wp_unslash($_POST['discussion']));
        }

        wp_send_json([
            'message'    => __('Settings saved successfully.', 'fluent-comments'),
            'discussion' => DiscussionSettings::get(),
        ], 200);
    }

    /**
     * Whether each enabled post type's template actually has our block or
     * shortcode in it. Block themes only: on a classic theme we place the
     * form ourselves and there is nothing to look for.
     *
     * The settings screen asks for this as it opens and again after a save,
     * and it is the only thing that asks. Resolving templates is a query
     * plus a walk over theme files, so it stays on this one screen rather
     * than running behind every page in wp-admin.
     *
     * @return void
     */
    public function scanTemplatesAjax()
    {
        Helper::verifyAdminAjax();

        wp_send_json([
            'is_block_theme' => Helper::isBlockTheme(),
            'templates'      => TemplateScanner::scan(),
        ], 200);
    }


    /**
     * A fresh install is already running: with no saved option the defaults
     * put FluentComments on `post` with native rejection on, so a site owner
     * who has not opened the screen still has a plugin changing how their
     * comments work.
     *
     * Not dismissible. Saving the screen once retires it, and that is the
     * only thing that should - a dismiss link buys silence without the site
     * owner ever having seen what the defaults are doing, which is the one
     * outcome this notice exists to prevent.
     *
     * Deliberately cheap - one autoloaded option and one user meta, no
     * template scanning. Whether the block has actually been placed is the
     * settings screen's Placement needed panel, which asks over ajax; that
     * question costs a query and a walk over theme files and does not belong
     * behind every page in wp-admin.
     *
     * @return void
     */
    public function maybeShowSetupNotice()
    {
        if (!current_user_can('manage_options') || Helper::isConfigured()) {
            return;
        }

        $screen = function_exists('get_current_screen') ? get_current_screen() : null;

        // They are already looking at it.
        if ($screen && strpos($screen->id, self::PAGE_SLUG) !== false) {
            return;
        }

        $settingsUrl = admin_url('edit-comments.php?page=' . self::PAGE_SLUG);
        ?>
        <div class="notice notice-info">
            <p>
                <strong><?php esc_html_e('FluentComments', 'fluent-comments'); ?>:</strong>
                <?php esc_html_e('Thanks for installing! Nothing has been set up yet, so the defaults are running: FluentComments handles comments on posts, and comments posted through any other form are rejected as spam.', 'fluent-comments'); ?>
            </p>
            <?php if (Helper::isBlockTheme()) : ?>
                <p>
                    <?php esc_html_e('You are on a block theme, so FluentComments does not place itself on your templates. Until you add the FluentComments block in the Site Editor or the [fluent_comments] shortcode, posts cannot take comments at all. The settings screen checks your templates and tells you where it is missing.', 'fluent-comments'); ?>
                </p>
            <?php endif; ?>
            <p>
                <a class="button button-primary" href="<?php echo esc_url($settingsUrl); ?>">
                    <?php esc_html_e('Configure FluentComments', 'fluent-comments'); ?>
                </a>
            </p>
        </div>
        <?php
    }

}
